[build]
  command = "yarn build"
  publish = "public/"

[build.environment]
  NODE_VERSION  = "10.15.0"
  YARN_VERSION  = "1.13.0"

[context.production.environment]
  DISQUS_SHORTNAME              = "chadlynet"
  GOOGLE_ANALYTICS_TRACKING_ID  = "UA-636144-7"
