---
id: cc6295c5-3b07-5888-a1ea-61288006f897
title: Installing NVidia Drivers for GTX 650 Ti Boost in Ubuntu 14.04
description: Watch someone struggle to update drivers in Linux.
date: '2015-04-04'
redirect_from:
  - /2015/04/nvidia-drivers
  - /2015/04/installing-nvidia-drivers-for-gtx-650-ti-boost-in-ubuntu-14-04
---

I was experiencing problems with banding in some games and during videos with the NVidia 331 drivers in Ubuntu. I decided to try the latest driver from NVidia for my card, (`346.47` as of right now).

**Spoiler:** The latest driver solves the banding issues and is much more performant.

I ran the following to determine my exact graphics card:

```
$ lspci | grep VGA
02:00.0 VGA compatible controller: NVIDIA Corporation GK106 [GeForce GTX 650 Ti Boost] (rev a1)
```

I then went to [NVidia](http://www.nvidia.com/Download/index.aspx?lang=en-us) to download the driver for my card.

At first, I just ran the `sh` file from NVidia without googling for anything hoping that the installer would guide me along the right path. I [booted into recovery mode](https://wiki.ubuntu.com/RecoveryMode) to install it. (hold `left shift` during the grub boot screen -> Advanced Settings -> Enable Networking -> Root Shell).

During the installation, it complained to me about the distribution provided pre-install script failing. I haven't figured out why that is happening yet, but I was able to just continue the installation.

Anyway, after the installation successfully finished, I rebooted to a blank screen with a flashing cursor in which I couldn't do anything. Ughh, why can't things just be easy?

I eventually found [this post](http://askubuntu.com/questions/162075/my-computer-boots-to-a-black-screen-what-options-do-i-have-to-fix-it) and then [this guide](http://askubuntu.com/questions/66328/how-do-i-install-the-latest-nvidia-drivers-from-the-run-file/423619#423619). If I would have just followed the guide completely from the beginning, everything would have probably worked fine.

The part that ended up making it all work for me was adding the file to `/etc/modprobe.d` to blacklist the nouveau driver. I found out later that an older NVidia installer (`NVIDIA-Linux-x86_64-340.76.run`) creates this file:

```
/etc/modprobe.d/nvidia-installer-disable-nouveau.conf
```

with contents:

```
# generated by nvidia-installer
blacklist nouveau
options nouveau modeset=0
```

while the latest `NVIDIA-Linux-x86_64-346.47.run` doesn't.

Anyway, long story short, just [follow the guide](http://askubuntu.com/questions/66328/how-do-i-install-the-latest-nvidia-drivers-from-the-run-file/423619#423619) if you want to install manual NVidia drivers. And for me, it solved a lot of graphics and performance issues I was having.