name: Trigger Netlify Build
on:
  schedule:
    # Run at 8AM UTC (3AM CT) daily
    - cron: '0 8 * * *'
jobs:
  build:
    name: POST to Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_URL }}
